apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: discord-bot

resources:
  - namespace.yaml
  - secret.yaml
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml

commonLabels:
  app: discord-bot
  managed-by: kustomize
